# Generated by Django 5.1.5 on 2025-02-13 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representantes',
            name='denominara',
        ),
    ]
