# Generated by Django 5.1.5 on 2025-01-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='serial_cliente',
            field=models.CharField(help_text='Serial Cliente', max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Serial'),
        ),
    ]
