# Generated by Django 5.1.5 on 2025-02-09 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('us_in', models.CharField(blank=True, max_length=150, null=True, verbose_name='Creado por')),
                ('fe_us_in', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('us_mo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Modificado por')),
                ('fe_us_mo', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('id', models.AutoField(help_text='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('url_contrato', models.URLField(blank=True, help_text='Ingrese la URL donde se encuentra el contrato.', null=True, verbose_name='URL del Contrato')),
                ('serial_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contatos', to='formulario.datos')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['serial_cliente'],
            },
        ),
    ]
