# Generated by Django 5.1.5 on 2025-02-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='representante',
            name='inactivo',
            field=models.BooleanField(default=True, help_text='Estado de actividad', verbose_name='Estado'),
        ),
    ]
