# Generated by Django 5.1.5 on 2025-02-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_remove_representantes_denominara'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidades',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección', max_length=250, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='entidades',
            name='denominara',
            field=models.CharField(blank=True, help_text='Se Denominará', max_length=120, null=True, verbose_name='Se Denominará'),
        ),
        migrations.AlterField(
            model_name='urbanismos',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección', max_length=250, null=True, verbose_name='Dirección'),
        ),
    ]
