# Generated by Django 5.1.5 on 2025-02-05 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_representante_inactivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos',
            name='sello_dorado_oficio',
        ),
        migrations.AddField(
            model_name='datos',
            name='nro_dorado_oficio',
            field=models.CharField(blank=True, help_text='Número Sello Dorado u Oficio', max_length=20, null=True, verbose_name='Número Sello Dorado u Oficio'),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('us_in', models.CharField(blank=True, max_length=150, null=True, verbose_name='Creado por')),
                ('fe_us_in', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('us_mo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Modificado por')),
                ('fe_us_mo', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('co_sector', models.CharField(help_text='Código del sector', max_length=6, primary_key=True, serialize=False, verbose_name='Código')),
                ('des_sector', models.CharField(help_text='Nombre del sector', max_length=60, verbose_name='Nombre')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sectores', to='formulario.parroquia')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'ordering': ['des_sector'],
            },
        ),
    ]
