# Generated by Django 5.1.5 on 2025-02-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_entidades_direccion_alter_entidades_denominara_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estados',
            name='iso_3166_2',
            field=models.CharField(blank=True, help_text='ISO_3166-2', max_length=4, null=True, verbose_name='iso_3166-2'),
        ),
    ]
